=== ExtendSKE/com.castsoftware.bpel.2.0/InstallScripts/Common/CAST_XMLDB_Format.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.0.5.906 (http://www.liquid-technologies.com)-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" name="table">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:element maxOccurs="unbounded" name="column">
                <xs:complexType>
                  <xs:attribute name="name" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:maxLength value="30" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="int" />
                        <xs:enumeration value="bool" />
                        <xs:enumeration value="num" />
                        <xs:enumeration value="string" />
                        <xs:enumeration value="fixedstring" />
                        <xs:enumeration value="date" />
                        <xs:enumeration value="text" />
                        <xs:enumeration value="binary" />
                        <xs:enumeration value="identity" />
                        <xs:enumeration value="rowid" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="nullable" type="xs:boolean" use="required" />
                  <xs:attribute name="description" use="optional">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9 ()?/.,+-_:!&amp;']*" />
                        <xs:maxLength value="255" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="length" type="xs:integer" use="optional" />
                  <xs:attribute name="default" type="xs:string" use="optional" />
                  <xs:attribute name="scale" type="xs:integer" />
                  <xs:attribute name="precision" type="xs:integer" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="index">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="column">
                      <xs:complexType>
                        <xs:attribute name="name" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:maxLength value="30" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="sort" use="optional">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="asc" />
                              <xs:enumeration value="desc" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:maxLength value="30" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="index" />
                        <xs:enumeration value="primary key" />
                        <xs:enumeration value="clustered index" />
                        <xs:enumeration value="unique index" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="platform">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="(((oracle|microsoft|sybase|udb|postgresql|all)[;,])+(oracle|microsoft|sybase|udb|postgresql|all)+|(oracle|microsoft|sybase|udb|postgresql|all)+)" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:maxLength value="30" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="description" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:maxLength value="255" />
                  <xs:pattern value="[a-zA-Z0-9 ()?/.,+-_:!&amp;']*" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="platform" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(((oracle|microsoft|sybase|udb|postgresql|all)[;,])+(oracle|microsoft|sybase|udb|postgresql|all)+|(oracle|microsoft|sybase|udb|postgresql|all)+)" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="temporary" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(((oracle|microsoft|sybase|udb|postgresql|all|none)[;])+(oracle|microsoft|sybase|udb|postgresql|all|none)+|(oracle|microsoft|sybase|udb|postgresql|all|none)+)" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="logging" type="xs:boolean" />
            <xs:attribute name="working" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="scope">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="scopetable">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="scopecolumn">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" />
                        <xs:attribute name="minvalue" type="xs:integer" />
                        <xs:attribute name="maxvalue" type="xs:integer" />
                        <xs:attribute name="type" type="xs:string" />
                        <xs:attribute name="value" type="xs:string" />
                        <xs:attribute name="mode" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="order" type="xs:string" use="optional" />
                  <xs:attribute name="filter" type="xs:string" />
                  <xs:attribute name="type" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="include">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ExtendSKE/com.castsoftware.bpel.2.0/InstallScripts/Common/set_tables.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CAST_XMLDB_Format.xsd" 
    name="OBJSET" version="1.0.0.0" >
	<table name="SET_Definitions" description="List of object sets" >
		<column name="SetId" type="int" nullable="false" description="" />
		<column name="SetName" type="string" nullable="false" length="255" description="Name of the set" />
		<column name="SetType" type="string" nullable="true" length="255" description="Type of set, DIAG_SCOPE by default" />
		<column name="SetProcedure" type="string" nullable="false" length="30" description="Name of procedure that fill Set_content" />
		<index name="IDX_SET_Definitions" type="index" >
			<column name="SetId" sort="asc" />
		</index>
	</table>
	<table name="SET_Contents" description="List of objects composing object sets" >
		<column name="SetId" type="int" nullable="false" description="" />
		<column name="ObjectId" type="int" nullable="false" description="" />
		<index name="IDX_SET_Contents" type="index" >
			<column name="SetId" sort="asc" />
			<column name="ObjectId" sort="asc" />
		</index>
		<index name="IDX_SET_Contents_Obj" type="index" >
			<column name="ObjectId" sort="asc" />
			<column name="SetId" sort="asc" />
		</index>
	</table>

	<scope name="OBJSET">
		<scopetable name="SET_Definitions" />
		<scopetable name="SET_Contents" />
	</scope>

	<scope name="OBJSETINIT">
		<scopetable name="SET_Definitions" filter="(SetId between 1187000 and 1187999)" />
	</scope>

</config>
